-- add these to your qb-core > shared.lua

["uwububbleteablueberry"] = {["name"] = "uwububbleteablueberry", ["label"] = "Berry Blue B-T", ["weight"] = 200, ["type"] = "item", ["image"] = "uwububbleteablueberry.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Lavender Tea with Blueberry Boba."}, 
["uwububbletearose"] = {["name"] = "uwububbletearose", ["label"] = "Rosey B-T", ["weight"] = 200, ["type"] = "item", ["image"] = "uwububbletearose.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Sakura Rose Tea with Vanilla Boba."}, 
["uwububbleteamint"] = {["name"] = "uwububbleteamint", ["label"] = "Minty B-T", ["weight"] = 200, ["type"] = "item", ["image"] = "uwububbleteamint.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Matcha Tea with Mint Boba."}, 
["uwupancake"] = {["name"] = "uwupancake", ["label"] = "uWu Savory Pancake", ["weight"] = 200, ["type"] = "item", ["image"] = "uwupancake.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Korean savory pancake made with scallions."}, 
["uwucupcake"] = {["name"] = "uwucupcake", ["label"] = "uWu Cupcake", ["weight"] = 200, ["type"] = "item", ["image"] = "uwucupcake.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Sugar Kitty Cupcake!"}, 
["uwuvanillasandy"] = {["name"] = "uwuvanillasandy", ["label"] = "uWu V-Icecream Sandy", ["weight"] = 200, ["type"] = "item", ["image"] = "uwuvanillasandy.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Sweet Vanilla Biscuit filled with Icecreamy!"}, 
["uwuchocsandy"] = {["name"] = "uwuchocsandy", ["label"] = "uWu C-Icecream Sandy", ["weight"] = 200, ["type"] = "item", ["image"] = "uwuchocsandy.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Sweet Chocolate Biscuit filled with Icecreamy!"}, 
["uwubudhabowl"] = {["name"] = "uwubudhabowl", ["label"] = "uWu Budha Bowl", ["weight"] = 200, ["type"] = "item", ["image"] = "uwubudhabowl.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Bowl of nourishment and balance."}, 
["uwusushi"] = {["name"] = "uwusushi", ["label"] = "uWu Sushi", ["weight"] = 200, ["type"] = "item", ["image"] = "uwusushi.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Designed as a window to your soul."}, 
["uwumisosoup"] = {["name"] = "uwumisosoup", ["label"] = "uWu Miso Soup", ["weight"] = 200, ["type"] = "item", ["image"] = "uwumisosoup.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Fungus never tasted so good!"}, 
["uwubentobox"] = {["name"] = "uwubentobox", ["label"] = "uWu Bento Box", ["weight"] = 200, ["type"] = "item", ["image"] = "uwubentobox.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "An uWu Selection with a surprise!"},

-- UwU Ingredients

["bb-flavoring"] = {["name"] = "bb-flavoring", ["label"] = "Bluebuerry Flavoring", ["weight"] = 200, ["type"] = "item", ["image"] = "bb-flavoring.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Blueberry flavoring for Bubble Tea!"},
["rose-flavoring"] = {["name"] = "rose-flavoring", ["label"] = "Rose Flavoring", ["weight"] = 200, ["type"] = "item", ["image"] = "rose-flavoring.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Rose flavoring for Bubble Tea!"},
["mint-flavoring"] = {["name"] = "mint-flavoring", ["label"] = "Mint Flavoring", ["weight"] = 200, ["type"] = "item", ["image"] = "mint-flavoring.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Mint flavoring for Bubble Tea!"},
["eggs"] = {["name"] = "eggs", ["label"] = "Cooking Eggs", ["weight"] = 200, ["type"] = "item", ["image"] = "eggs.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Eggs...common cooking ingredient."},
["flour"] = {["name"] = "flour", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "flour.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Flour...common cooking ingredient."},
["milk"] = {["name"] = "milk", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "milk.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Milk...common cooking ingredient."},
["miso-paste"] = {["name"] = "miso-paste", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "miso-paste.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Miso paste. Mix this with water to make a soup!"},
["tapiokaballs"] = {["name"] = "tapiokaballs", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "tapiokaballs.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Tapioka balls typically seen in making Bubble Tea!"},
["tea"] = {["name"] = "tea", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "tea.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Its just tea..."},
["tofu"] = {["name"] = "tofu", ["label"] = "Flour", ["weight"] = 200, ["type"] = "item", ["image"] = "tofu.png", ["unique"] = false, ["useable"] = true, ["shouldClose"] = true, ["combinable"] = nil, ["description"] = "Tofu. Not quite as tasty as real meat but to each their own..."},
