Config = {}

Config.GaragePedLocations = {
    --{coords = vector4(-1178.588, -891.9196, 13.799622, 302.58825)}, (unused)
}

Config.SQL = 'oxmysql' --- oxmysql or ghmattisql

Config.Items = {
label = "Shop",
    slots = 23,
    items = {
        [1] = {
            name = "uwububbleteablueberry",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "uwububbletearose",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "uwububbleteamint",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "uwupancake",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "uwucupcake",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "uwuvanillasandy",
            price = 3,
            amount = 20,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "uwuchocsandy",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "uwubudhabowl",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "uwusushi",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "uwumisosoup",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "uwubentobox",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "burger-toy1",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "burger-toy2",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "bb-flavoring",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "rose-flavoring",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "mint-flavoring",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "eggs",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "flour",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "milk",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "miso-paste",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "tapiokaballs",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "tea",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "tofu",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "water_bottle",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 24,
        },
    }
}